### ISSUE TITLE
index adjustments and fixes / 调整水滴索引生成和使用

### ISSUE THREAD

**Issue by simlecode** [ipfs-force-community/droplet#343]
### 问题

1. 已生成的索引还需检查是否生成 topIndex，若未生成还需生成后写入到 MongoDB
2. shard 由于本地存储不能共享问题 

> topIndex 主要是在查某一段数据的时候会用到，使用 MongoDB 存储，方便所有 droplet 共享

### 解决

对于上面的问题 2，shard 支持存储到 MySQL

### dagstore

调整 dagstore 库 管理 shard 的接口

#### 工具

* 给 piece 生成索引
* 根据索引生成 shard，shard 支持存储在 badger 或者 MySQL
* 根据索引生成 topIndex，topIndex 支持写入到 badger 和 MongoDB

**Comment by Fatman13** [comment]
是 tiger 提出的问题引发的？

- [ ] https://filecoinproject.slack.com/archives/C028PCH8L31/p1686902397087279

**Comment by simlecode** [comment]
> 是 tiger 提出的问题引发的？

不是，主要玄翎要用
