### ISSUE TITLE
check deal proposal json agent name / 检查 deal proposal json agent name

### ISSUE THREAD

**Issue by Fatman13** [ipfs-force-community/droplet#346]
先看看当前是啥？需不需要改成 droplet，还是就算了？(CIDgravity的人在问) 不过我看好像没有 agent 这个参数？

- [ ] https://github.com/filecoin-project/venus/issues/5669#issuecomment-1556607936

**Comment by LinZexiao** [comment]
有的, 我们目前的参数是这样的:
```go
Agent:              "droplet",
```
