### ISSUE TITLE
add more metrics / 添加更多metrics

### ISSUE THREAD

**Issue by elvin-du** [ipfs-force-community/droplet#368]
### Droplet / 水滴

- [X] droplet
- [X] droplet-client
- [ ] 文档 / docs

### Description / 描述

为了更好的监控，运维，添加如下metrics：

组件名称 | 指标 | label | value | name
-- | -- | -- | -- | --
droplet|  api接口启动状态  | \ |  0或1来表示是否正常启动 | api/state
droplet| 检索计数 |   | 检索计数 (0:fail,1:succeed) | retrieval/transfer_event
droplet| dagstore list-shards中不同状态piece数量 | \ | piece数量  | shard/num

**Comment by Fatman13** [comment]
兄弟们这个 issue 冲一冲，冲完，就去拿 metrics milestone 3 的 grant 了。
