### ISSUE TITLE
[droplet-client] 下单报query ask failed。

### ISSUE THREAD

**Issue by BaiYuTest** [ipfs-force-community/droplet#416]
### Droplet / 水滴

- [ ] droplet
- [X] droplet-client
- [ ] 文档 / docs

### Version / 版本

```text
droplet-client version v2.8.0+git.dacf390
```

### Describe the Bug / 描述

在设置了下单价格且钱包地址注册到gateway的前提下进行下单，报错：Error: failed to query ask: bls signature failed to verify

### Logging Information / 日志

```text
./droplet-client data import 9.png
Import 1692865190720248675, Root bafykbzacecnpkfnjutdjthm2yveylbg3xw3exkilzi6w5uuuiearjfrdvobu4
root@calib-venus-132:~/droplet#  ./droplet-client storage deals init
Data CID (from droplet-client data import): bafykbzacecnpkfnjutdjthm2yveylbg3xw3exkilzi6w5uuuiearjfrdvobu4
.. calculating data size
PieceCid:  baga6ea4seaqfwtemwtlpiil73z3fnrelflmldtjwumd7uq52ydoobokt7b2hgaa  PayLoadSize: 40162647 PieceSize: 67108864
Deal duration (days): 380
Miner Addresses (f0.. f0..), none to find: f023456
.. querying miner asks
Error: failed to query ask: bls signature failed to verify
```

### Repo Steps / 重现步骤

./droplet-client data import xxx
./droplet-client storage deals init
Data CID (from droplet-client data import): xxx
PieceCid:  baga6ea4seaqfwtemwtlpiil73z3fnrelflmldtjwumd7uq52ydoobokt7b2hgaa  PayLoadSize: 40162647 PieceSize: 67108864
Deal duration (days): 380
Miner Addresses (f0.. f0..), none to find: f023456
.. querying miner asks
Error: failed to query ask: bls signature failed to verify

**Comment by simlecode** [comment]
修复：https://github.com/filecoin-project/venus/pull/6130
