### ISSUE TITLE
支持 Direct data onboarding 

### ISSUE THREAD

**Issue by simlecode** [ipfs-force-community/droplet#425]
### Droplet / 水滴

- [X] droplet
- [X] droplet-client
- [X] 文档 / docs

### Description / 描述

[Direct data onboarding](https://github.com/filecoin-project/FIPs/discussions/730) 一种新的 deal 模式。

### droplet client

1. piece 管理，用来管理切割出来的piece，并存储到数据库，方便 direct deal 发单时使用
    * 导入 piece
    * 列出 piece
2. 发布 direct deal
    * 支持同时给多个矿工发单
    * 支持根据手动输入的piece信息
    * 支持根据已存储的 piece 信息发单
3. 查询 direct deal 分配情况

### droplet 

1. 导入 direct deal，类似离线订单的导入
    * 支持不计算 commP
    * 支持不把 piece 拷贝到 piece storage，方便孵化器使用
2. 存储 direct deal，需要更新订单状态？
3. 为 direct deal 生成索引？
4. droplet 与 damocles 的交互是否需要调整？

**Comment by Fatman13** [comment]
元神，启动！
