### ISSUE TITLE
[droplet] 支持 spark 检索

### ISSUE THREAD

**Issue by simlecode** [ipfs-force-community/droplet#530]
### Droplet / 水滴

- [X] droplet
- [ ] droplet-client
- [ ] 文档 / docs

### Description / 描述

1. 支持把 Index 发布到ipni
2. 增加命令管理 Index 
3. 调整表结构，增加 announce_to_ipni 字段
4. DDO订单接口增加 SkipAnnounceToIPNI 字段
5. 调整 http 检索逻辑  
6. 检查 https://filspark.com/troubleshooting-miner-score#block-7e10034eb61e417b9a69383b1e15018f

https://bajtos.grafana.net/public-dashboards/9af156c3266d4d8384385623d0d2a76c?orgId=1&from=1707295398643&to=1716023088195

![image](https://github.com/ipfs-force-community/droplet/assets/69969590/0cf1b577-e7f3-4a4b-89da-b6cd42e356d2)

**Comment by yann-y** [comment]
现在droplet还不支持spark 是吧

**Comment by simlecode** [comment]
> 现在droplet还不支持spark 是吧

是的

**Comment by yann-y** [comment]
计划多久开发完成乃？

**Comment by simlecode** [comment]
一个月左右

**Comment by kikyou1234** [comment]
为什么用了droplet没有检索率呢？

**Comment by simlecode** [comment]
@kikyou1234 已经可以检索了，用最新的 master 分支，文档：https://github.com/ipfs-force-community/droplet/blob/master/docs/zh/spark.md
