### ISSUE TITLE
market-client can limit the number of days per order

### ISSUE THREAD

**Issue by cloudxin** [ipfs-force-community/droplet#7]
When the market client places an order, there is no limit on the number of days to place an order; The default real order is stored for a minimum of 180 days and a maximum of 540 days.

market-client deal
/root/.marketclient
Data CID (from lotus client import): bafykbzaceciyctgphnwj6sxashn55puodo62bk4n4kkqhgw4fwkchbvq2qlw
.. calculating data size
PieceCid:  baga6ea4seaqhcwxs566wheq7yn5evm22xtpiv6usnqtou44vbz2zsfdmeyiaeq  PayLoadSize: 13959883139 PieceSize: 17179869184
Deal duration (days): **999999999999999999**
Miner Addresses (f0.. f0..), none to find: f01111
.. querying miner asks
Proposing from f3v5shsytrnz7ycr7ou4yxq2nf2xm34idnvfgnm6wyru7lrmu2ykuvtte2hq6rk2v3qttrsysvssr42cxt6a
	Balance: 13762.152500344563313485 FIL

Piece size: 16GiB (Payload size: 13GiB)
Duration: 1942802h0m29.571268608s
Total price: ~1.86508992 FIL (0.000000008 FIL per epoch)
Verified: false

Accept (yes/no): yes
.. executing
Deal (f019411) CID: bafyreihxyph3pqm47teqtzqkdbs6nmpjkuu74jjcb2esidklrmzesw6le

**Comment by Fatman13** [comment]
21 年的，先关掉了。
