### ISSUE TITLE
market-client usage problems

### ISSUE THREAD

**Issue by cloudxin** [ipfs-force-community/droplet#8]
After the wrong miner number for the first time, enter the correct check failure again

./market-client deal
/root/.marketclient
Data CID (from lotus client import): 540
Error: parsing cid string: selected encoding not supported
Data CID (from lotus client import): bafykbzacebfy3lbvxvgfnzc3fd5wpugtqf4gyb67hywifks3zdtczemzsbfg
.. calculating data size
PieceCid:  baga6ea4seaqmobo7ajlhdrwozyrb7fhx6ey7j22yfj5t4uzlbivbz5a5yufiygy  PayLoadSize: 13495574905 PieceSize: 17179869184
Deal duration (days): 530
Miner Addresses (f0.. f0..), none to find: f01941
.. querying miner asks
Error: failed to get peerID for miner: failed to load miner actor state: unknown actor code bafkqadlgnfwc6nrpmfrwg33vnz2a
Miner Addresses (f0.. f0..), none to find: **f019111**

**Comment by Fatman13** [comment]
21 年的，先关掉了。
